<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Primary Meta Tags -->
    <title>RifleWorks Business Solutions - Premier Staffing & Business Services in Rifle, Colorado</title>
    <meta name="title" content="RifleWorks Business Solutions - Premier Staffing & Business Services in Rifle, Colorado">
    <meta name="description" content="RifleWorks offers employment staffing, bookkeeping, payroll, and business support services in Rifle, Colorado. Over 30 years of trusted excellence serving Western Slope businesses.">
    <meta name="keywords" content="Rifle Colorado staffing, employment agency Rifle, bookkeeping services Rifle, payroll services Western Slope, temporary staffing Rifle Colorado, permanent placement Colorado, small business support Rifle, Garfield County employment">
    <meta name="author" content="RifleWorks Business Solutions">
    <meta name="robots" content="index, follow">
    <link rel="canonical" href="https://rifleworks.biz/">
    
    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="business.business">
    <meta property="og:title" content="RifleWorks Business Solutions - Premier Staffing & Business Services">
    <meta property="og:description" content="Over 30 years of trusted business support services in Rifle, Colorado. Employment staffing, bookkeeping, payroll, and professional business solutions.">
    <meta property="og:image" content="https://rifleworks.biz/images/rifleworks-og-image.jpg">
    <meta property="og:url" content="https://rifleworks.biz">
    <meta property="og:site_name" content="RifleWorks Business Solutions">
    <meta property="og:locale" content="en_US">
    
    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="RifleWorks Business Solutions - Rifle, Colorado">
    <meta name="twitter:description" content="Premier staffing & business services in Rifle, Colorado. 30+ years of excellence.">
    <meta name="twitter:image" content="https://rifleworks.biz/images/rifleworks-twitter-card.jpg">
    
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    
    <!-- Preconnect for performance -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="dns-prefetch" href="https://cdn.jsdelivr.net">
    
    <!-- Fonts and CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.4.0/css/all.min.css">
    
    <!-- Netlify Identity Widget -->
    <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
    
    <style>
        :root {
            --primary-green: #0d4f3c;
            --copper: #b85450;
            --amber: #f4a261;
            --cream: #faf0e6;
            --charcoal: #2a2a2a;
            --light-green: #e6f3f0;
        }
        
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Inter', sans-serif;
            line-height: 1.6;
            color: #2d3748;
            overflow-x: hidden;
        }
        
        .gradient-bg {
            background: linear-gradient(135deg, var(--primary-green) 0%, #1a5f4a 100%);
        }

        .hero-overlay {
            background: linear-gradient(rgba(13, 79, 60, 0.8), rgba(26, 95, 74, 0.9)),
                        url('https://cdn.allaspen.com/images/content/3874_hcCP0_Rifle_CO_lg.jpg') center/cover;
        }

        .card-hover {
            transition: all 0.3s ease;
            cursor: pointer;
        }

        .card-hover:hover {
            transform: translateY(-8px);
            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);
        }

        .btn-primary {
            background: linear-gradient(135deg, var(--copper) 0%, #d16560 100%);
            transition: all 0.3s ease;
        }

        .btn-primary:hover {
            background: linear-gradient(135deg, #d16560 0%, var(--copper) 100%);
            transform: translateY(-2px);
            box-shadow: 0 8px 20px rgba(184, 84, 80, 0.3);
        }

        .btn-secondary {
            background: transparent;
            border: 2px solid var(--amber);
            color: var(--amber);
            transition: all 0.3s ease;
        }

        .btn-secondary:hover {
            background: var(--amber);
            color: var(--primary-green);
            transform: translateY(-2px);
        }

        .text-gradient {
            background: linear-gradient(135deg, var(--amber) 0%, var(--copper) 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }

        .section-bg {
            background: linear-gradient(135deg, var(--cream) 0%, #f7f1ec 100%);
        }

        .modal {
            display: none;
            position: fixed;
            z-index: 1000;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.8);
            backdrop-filter: blur(5px);
        }

        .modal-content {
            background-color: white;
            margin: 5% auto;
            padding: 0;
            border-radius: 15px;
            width: 90%;
            max-width: 600px;
            max-height: 90vh;
            overflow-y: auto;
            animation: slideIn 0.3s ease;
        }

        @keyframes slideIn {
            from { opacity: 0; transform: translateY(-50px); }
            to { opacity: 1; transform: translateY(0); }
        }

        .close {
            color: #aaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
            padding: 10px 20px;
            cursor: pointer;
        }

        .close:hover {
            color: var(--copper);
        }

        .form-control {
            width: 100%;
            padding: 12px 16px;
            border: 2px solid #e2e8f0;
            border-radius: 8px;
            font-size: 16px;
            transition: all 0.3s ease;
            background-color: white;
        }

        .form-control:focus {
            outline: none;
            border-color: var(--amber);
            box-shadow: 0 0 0 3px rgba(244, 162, 97, 0.1);
        }

        .job-card {
            background: white;
            border-radius: 12px;
            padding: 1.5rem;
            margin: 1rem 0;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);
            border-left: 4px solid var(--amber);
            transition: all 0.3s ease;
        }

        .job-card:hover {
            transform: translateY(-2px);
            box-shadow: 0 8px 20px rgba(0, 0, 0, 0.1);
        }

        .stats-counter {
            font-size: 3rem;
            font-weight: 800;
            color: var(--amber);
        }

        .service-icon {
            width: 60px;
            height: 60px;
            background: linear-gradient(135deg, var(--amber), var(--copper));
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            font-size: 24px;
            margin: 0 auto 1rem;
        }

        .loading {
            text-align: center;
            padding: 2rem;
            color: var(--primary-green);
        }

        @media (max-width: 768px) {
            .hero-content h1 {
                font-size: 2.5rem;
            }
            
            .modal-content {
                width: 95%;
                margin: 10% auto;
            }
        }
    </style>
</head>
<body class="bg-gray-50">

    <!-- Navigation -->
    <nav class="fixed w-full z-50 bg-white shadow-lg">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex justify-between items-center py-4">
                <div class="flex items-center space-x-3">
                    <img src="https://cdn1.genspark.ai/user-upload-image/gpt_image_generated/88c7aac3-6618-4eb9-b842-7a811d16c193" alt="RifleWorks Logo" class="h-12 w-auto">
                    <div>
                        <h1 class="text-2xl font-bold" style="color: var(--primary-green);">RifleWorks</h1>
                        <p class="text-sm text-gray-600">Business Solutions</p>
                    </div>
                </div>
                <div class="hidden md:flex space-x-8">
                    <a href="#home" class="nav-link text-gray-700 hover:text-amber-500 transition-colors">Home</a>
                    <a href="#services" onclick="scrollToSection('services')" class="nav-link text-gray-700 hover:text-amber-500 transition-colors">Services</a>
                    <a href="#about" onclick="scrollToSection('about')" class="nav-link text-gray-700 hover:text-amber-500 transition-colors">About</a>
                    <a href="#jobs" onclick="scrollToSection('jobs')" class="nav-link text-gray-700 hover:text-amber-500 transition-colors">Careers</a>
                    <a href="#contact" onclick="scrollToSection('contact')" class="nav-link text-gray-700 hover:text-amber-500 transition-colors">Contact</a>
                </div>
                <button onclick="openModal('jobModal')" class="btn-primary text-white px-6 py-2 rounded-lg">
                    Apply Now
                </button>
            </div>
        </div>
    </nav>

    <!-- Hero Section -->
    <section class="hero-overlay min-h-screen flex items-center">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
            <div class="grid lg:grid-cols-2 gap-12 items-center">
                <div class="hero-content text-white">
                    <div class="mb-6">
                        <span class="inline-block px-4 py-2 bg-amber-500 text-green-900 rounded-full text-sm font-semibold mb-4">
                            <span id="years-badge">30+</span> Years of Excellence
                        </span>
                    </div>
                    <h1 class="text-5xl lg:text-6xl font-bold leading-tight mb-6">
                        <span id="hero-title-1">Strategic Solutions</span>
                        <span class="text-gradient block" id="hero-title-2">for Business Growth</span>
                    </h1>
                    <p class="text-xl text-gray-200 mb-8 leading-relaxed" id="hero-subtitle">
                        RifleWorks delivers efficient, reliable, and confidential business support services. 
                        Specializing in helping small businesses thrive through tailored solutions and professional expertise in Rifle, Colorado.
                    </p>
                    <div class="flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-4">
                        <button onclick="openModal('jobModal')" class="btn-primary px-8 py-4 rounded-lg text-lg font-semibold">
                            <i class="fas fa-briefcase mr-2"></i>Find Your Career
                        </button>
                        <button onclick="scrollToSection('services')" class="btn-secondary px-8 py-4 rounded-lg text-lg font-semibold">
                            Our Services
                        </button>
                    </div>
                </div>
                <div class="hidden lg:block">
                    <div class="bg-white bg-opacity-10 backdrop-filter backdrop-blur-lg rounded-2xl p-8 text-center">
                        <div class="service-icon mx-auto mb-4">
                            <i class="fas fa-award"></i>
                        </div>
                        <h3 class="text-2xl font-bold text-white mb-2"><span id="years-stat">30+</span> Years</h3>
                        <p class="text-gray-200">of Trusted Excellence</p>
                        <div class="mt-6 grid grid-cols-2 gap-4 text-center">
                            <div>
                                <div class="text-3xl font-bold text-amber-300"><span id="businesses-stat">500+</span></div>
                                <div class="text-sm text-gray-300">Businesses Served</div>
                            </div>
                            <div>
                                <div class="text-3xl font-bold text-amber-300"><span id="jobs-stat">1000+</span></div>
                                <div class="text-sm text-gray-300">Jobs Placed</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Services Section -->
    <section id="services" class="py-20 section-bg">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="text-center mb-16">
                <h2 class="text-4xl lg:text-5xl font-bold mb-6" style="color: var(--primary-green);">
                    Our Core Services
                </h2>
                <p class="text-xl text-gray-600 max-w-3xl mx-auto">
                    Comprehensive business solutions designed to help your organization grow and succeed in Rifle, Colorado and the Western Slope region.
                </p>
            </div>

            <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
                <!-- Static service cards for now - can be made dynamic later -->
                <div class="card-hover bg-white rounded-2xl p-8 text-center shadow-lg">
                    <div class="service-icon">
                        <i class="fas fa-users"></i>
                    </div>
                    <h3 class="text-2xl font-bold mb-4" style="color: var(--primary-green);">Employment Staffing</h3>
                    <p class="text-gray-600 mb-6">
                        Permanent placements, temp-to-hire, and employee leasing services. We connect qualified candidates with the right opportunities.
                    </p>
                    <ul class="text-left text-gray-600 space-y-2 mb-6">
                        <li><i class="fas fa-check text-amber-500 mr-2"></i>Temporary Staffing</li>
                        <li><i class="fas fa-check text-amber-500 mr-2"></i>Permanent Placement</li>
                        <li><i class="fas fa-check text-amber-500 mr-2"></i>Employee Leasing</li>
                        <li><i class="fas fa-check text-amber-500 mr-2"></i>Skills Assessment</li>
                    </ul>
                    <button onclick="openModal('jobModal')" class="btn-primary w-full py-3 rounded-lg">
                        Apply for Jobs
                    </button>
                </div>

                <div class="card-hover bg-white rounded-2xl p-8 text-center shadow-lg">
                    <div class="service-icon">
                        <i class="fas fa-calculator"></i>
                    </div>
                    <h3 class="text-2xl font-bold mb-4" style="color: var(--primary-green);">Bookkeeping & Payroll</h3>
                    <p class="text-gray-600 mb-6">
                        Accurate financial records and streamlined payroll processes to keep your business running smoothly.
                    </p>
                    <ul class="text-left text-gray-600 space-y-2 mb-6">
                        <li><i class="fas fa-check text-amber-500 mr-2"></i>Monthly Bookkeeping</li>
                        <li><i class="fas fa-check text-amber-500 mr-2"></i>Payroll Processing</li>
                        <li><i class="fas fa-check text-amber-500 mr-2"></i>Tax Preparation</li>
                        <li><i class="fas fa-check text-amber-500 mr-2"></i>Financial Reporting</li>
                    </ul>
                    <button onclick="openModal('contactModal')" class="btn-secondary w-full py-3 rounded-lg border-2">
                        Learn More
                    </button>
                </div>

                <div class="card-hover bg-white rounded-2xl p-8 text-center shadow-lg">
                    <div class="service-icon">
                        <i class="fas fa-file-alt"></i>
                    </div>
                    <h3 class="text-2xl font-bold mb-4" style="color: var(--primary-green);">Secretarial Services</h3>
                    <p class="text-gray-600 mb-6">
                        Administrative support that saves time and reduces overhead costs for your business operations.
                    </p>
                    <ul class="text-left text-gray-600 space-y-2 mb-6">
                        <li><i class="fas fa-check text-amber-500 mr-2"></i>Administrative Support</li>
                        <li><i class="fas fa-check text-amber-500 mr-2"></i>Document Management</li>
                        <li><i class="fas fa-check text-amber-500 mr-2"></i>Data Entry</li>
                        <li><i class="fas fa-check text-amber-500 mr-2"></i>Office Organization</li>
                    </ul>
                    <button onclick="openModal('contactModal')" class="btn-secondary w-full py-3 rounded-lg border-2">
                        Get Quote
                    </button>
                </div>

                <div class="card-hover bg-white rounded-2xl p-8 text-center shadow-lg">
                    <div class="service-icon">
                        <i class="fas fa-rocket"></i>
                    </div>
                    <h3 class="text-2xl font-bold mb-4" style="color: var(--primary-green);">New Business Setup</h3>
                    <p class="text-gray-600 mb-6">
                        Expert guidance to build a strong foundation for your new business venture in Colorado.
                    </p>
                    <ul class="text-left text-